"""empty message

Revision ID: 5cca950067f7
Revises: efb2d7e47ecd
Create Date: 2017-11-02 11:49:34.969697

"""

# revision identifiers, used by Alembic.
revision = '5cca950067f7'
down_revision = 'efb2d7e47ecd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
