"""empty message

Revision ID: b7aebde2fbdf
Revises: 5e37db731212
Create Date: 2017-11-04 17:37:32.925607

"""

# revision identifiers, used by Alembic.
revision = 'b7aebde2fbdf'
down_revision = '5e37db731212'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
